### ISSUE TITLE
git conflict marker in snippets

### ISSUE THREAD

**Issue by rbudiharso** [andrewstuart/vim-kubernetes#4]
You have a git conflict marker in [here](https://github.com/andrewstuart/vim-kubernetes/blob/b1cd78d17c19c6e42899006ed21d20cc2d2f776c/UltiSnips/yaml.snippets#L538) which breaks ultisnip

**Comment by luisdavim** [comment]
same issue here.

**Comment by andrewstuart** [comment]
Argh, sorry about that. Should be fixed now. :-)
